version: 2

models:
  - name: dim_customers
    description: "Customer dimension (transactional table)."
    columns:
      - name: customer_id
        tests: [not_null, unique]
      - name: email
        tests: [not_null]

  - name: dim_products
    description: "Product dimension (transactional table)."
    columns:
      - name: product_id
        tests: [not_null, unique]
      - name: price
        tests: [not_null]

  - name: dim_date
    description: "Date dimension for reporting"

  - name: fact_order_items
    description: "Item-level facts (one row per product in an order)."
    columns:
      - name: order_item_id
        tests: [not_null, unique]
      - name: order_id
        tests: [not_null]
      - name: product_id
        tests: [not_null]

  - name: fact_orders
    description: "Order-level facts (one row per order)."
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
        tests: [not_null]
